// share-theme — 分享页 token 快照与样式单源（T13 / ARC-5：分享页 token 快照导出）
//
// 分享页是站外唯一面（/ob_share/<token>，无宿主 CSS 变量环境），样式必须**独立可离线**：
//   ① SHARE_TOKEN_SNAPSHOT = 宿主 dsw 主题（dsh-client-ui-theme）token 的具体取值快照，
//      light/dark 双份（明暗跟随访客系统偏好——分享页无宿主主题开关，见 task-13-report §3 Ruling）；
//   ② 规则区只消费 var(--dsw-*)，零色值字面量（禁自造色板——色值只在快照块=快照导出唯一取值处）；
//   ③ 消费面与 web/src/styles.css 同 token 名（主 UI/分享页零漂移，TECH §3.9.5 方案 A）。
//
// 快照来源与刷新：tools/extract-token-snapshot.mjs 从宿主主题源导出（--write 回写本文件的
// 生成块；生成块标记见下，块内取值勿手改）。dsh 升版改色板后重跑该工具刷新快照
//（provenance=SHARE_SNAPSHOT_SOURCE）。锁形见 test/share-theme.test.mjs：闭包零悬空/零外链/
// 明暗同名集/规则区零色值/主 UI 零漂移/真分享页内联。

/** 快照来源（provenance：工具+主题源+导出口径） */
export const SHARE_SNAPSHOT_SOURCE =
  'tools/extract-token-snapshot.mjs ← dsh-client-ui-theme/lib/client.js（body / body[data-ds-dark-theme]）'

/** dsw token 快照（light/dark 同名集；值=宿主主题解析后的字面取值） */
export const SHARE_TOKEN_SNAPSHOT = {
  // SNAPSHOT-BEGIN: generated by tools/extract-token-snapshot.mjs
  light: {
    "--dsw-alias-bg-base": "#fff",
    "--dsw-alias-bg-layer-1": "#fff",
    "--dsw-alias-border-l1": "#0000000a",
    "--dsw-alias-border-l2": "#0000001a",
    "--dsw-alias-border-l3": "#0000001f",
    "--dsw-alias-file-diff-added-bg": "#e6f4e7",
    "--dsw-alias-file-diff-deleted-bg": "#fce6e2",
    "--dsw-alias-interactive-bg-hover": "#2631480f",
    "--dsw-alias-label-primary": "#0f1115",
    "--dsw-alias-label-secondary": "#61666b",
    "--dsw-alias-label-tertiary": "#81858c",
    "--dsw-alias-link": "#4176e6",
    "--dsw-alias-markdown-code-block": "#f9fafb",
    "--dsw-alias-markdown-inline-code": "#fafafa",
    "--dsw-alias-state-business-primary": "#4176e6",
    "--dsw-alias-state-error-primary": "#ec1313",
    "--dsw-alias-state-success-primary": "#22c55e",
    "--dsw-alias-state-warn-label": "#dd8629",
    "--dsw-alias-state-warn-primary": "#f59e0b",
    "--dsw-alias-state-warn-tertiary": "#fef5e7",
    "--dsw-font-family": "-apple-system, BlinkMacSystemFont, \"Segoe UI\", \"PingFang SC\", \"Hiragino Sans GB\", \"Microsoft YaHei\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    "--dsw-font-m-18-font-size": "16px",
    "--dsw-font-markdown-code-block-font-family": "\"SF Mono\", \"JetBrains Mono\", \"Fira Code\", Consolas, \"Liberation Mono\", Menlo, Courier, \"PingFang SC\", \"Microsoft YaHei\"",
    "--dsw-font-xs-13-font-size": "13px",
    "--dsw-radius-sm": "8px",
    "--dsw-radius-xs": "4px",
  },
  dark: {
    "--dsw-alias-bg-base": "#151517",
    "--dsw-alias-bg-layer-1": "#232324",
    "--dsw-alias-border-l1": "#ffffff0f",
    "--dsw-alias-border-l2": "#ffffff1f",
    "--dsw-alias-border-l3": "#ffffff29",
    "--dsw-alias-file-diff-added-bg": "#1f3124",
    "--dsw-alias-file-diff-deleted-bg": "#3c1f1b",
    "--dsw-alias-interactive-bg-hover": "#ffffff14",
    "--dsw-alias-label-primary": "#f9fafb",
    "--dsw-alias-label-secondary": "#cfd3d6",
    "--dsw-alias-label-tertiary": "#adb2b8",
    "--dsw-alias-link": "#7aaaff",
    "--dsw-alias-markdown-code-block": "#1b1b1c",
    "--dsw-alias-markdown-inline-code": "#292929",
    "--dsw-alias-state-business-primary": "#7aaaff",
    "--dsw-alias-state-error-primary": "#f25a5a",
    "--dsw-alias-state-success-primary": "#22c55e",
    "--dsw-alias-state-warn-label": "#dd8629",
    "--dsw-alias-state-warn-primary": "#f59e0b",
    "--dsw-alias-state-warn-tertiary": "#27241f",
    "--dsw-font-family": "-apple-system, BlinkMacSystemFont, \"Segoe UI\", \"PingFang SC\", \"Hiragino Sans GB\", \"Microsoft YaHei\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    "--dsw-font-m-18-font-size": "16px",
    "--dsw-font-markdown-code-block-font-family": "\"SF Mono\", \"JetBrains Mono\", \"Fira Code\", Consolas, \"Liberation Mono\", Menlo, Courier, \"PingFang SC\", \"Microsoft YaHei\"",
    "--dsw-font-xs-13-font-size": "13px",
    "--dsw-radius-sm": "8px",
    "--dsw-radius-xs": "4px",
  }
  // SNAPSHOT-END: generated by tools/extract-token-snapshot.mjs
}

/** 分享页 CSS：快照块（内联自洽）+ 规则区（零色值字面量，全走 var(--dsw-*)） */
export function shareCss() {
  const snap = (tag, map) => `${tag}{${Object.entries(map).map(([k, v]) => `${k}:${v}`).join(';')}}`
  const snapshotCss = [
    '/* dsw token snapshot（ARC-5 分享页快照导出；来源 tools/extract-token-snapshot.mjs） */',
    snap(':root', SHARE_TOKEN_SNAPSHOT.light),
    `@media (prefers-color-scheme: dark){${snap('body', SHARE_TOKEN_SNAPSHOT.dark)}}`,
  ].join('\n')
  return `${snapshotCss}\n${SHARE_RULES}`
}

// ── 分享页规则区（服务端直出页面样式；字阶派生 --dsh-content-font-size：display ×1.6 /
//    阅读 ×1 / caption ×0.75，TECH §3.10.4 同款）───────────────────────────────────
const SHARE_RULES = `body{font-family:var(--dsw-font-family);font-size:var(--dsh-content-font-size,16px);line-height:1.7;color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-base);max-width:52rem;margin:2rem auto;padding:0 1rem}
main{overflow-wrap:break-word}
header h1{line-height:1.4;margin:0 0 .25em}
h1,h2{font-size:calc(var(--dsh-content-font-size,16px) * 1.6);line-height:1.4;margin:1em 0 .5em}
h3,h4,h5,h6{line-height:1.4;margin:1em 0 .5em}
pre{background:var(--dsw-alias-markdown-code-block);border:1px solid var(--dsw-alias-border-l2);border-radius:var(--dsw-radius-sm);padding:.75rem;overflow:auto}
code{background:var(--dsw-alias-markdown-inline-code);font-family:var(--dsw-font-markdown-code-block-font-family);padding:.1rem .3rem;border-radius:var(--dsw-radius-xs)}
pre code{background:inherit;padding:0}
table{border-collapse:collapse}
th,td{border:1px solid var(--dsw-alias-border-l2);padding:.35rem .6rem}
blockquote{border-left:3px solid var(--dsw-alias-border-l3);color:var(--dsw-alias-label-secondary);margin:1em 0;padding:4px 16px}
a{color:var(--dsw-alias-link)}
.ob-link-blocked{color:var(--dsw-alias-state-error-primary);text-decoration:line-through}
.ob-redact{background:var(--dsw-alias-state-warn-tertiary);color:var(--dsw-alias-state-warn-label);border-left:4px solid var(--dsw-alias-state-warn-primary);padding:.5rem .75rem}
form{border:1px solid var(--dsw-alias-border-l2);border-radius:var(--dsw-radius-sm);background:var(--dsw-alias-bg-layer-1);padding:.75rem;margin:1rem 0}
textarea,input{width:100%;box-sizing:border-box;font:inherit;color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-base);border:1px solid var(--dsw-alias-border-l2);border-radius:var(--dsw-radius-xs)}
button{font:inherit;width:auto;padding:.35rem 1rem;margin:.5rem .5rem 0 0;color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-layer-1);border:1px solid var(--dsw-alias-border-l2);border-radius:var(--dsw-radius-sm);cursor:pointer}
button:hover{background:var(--dsw-alias-interactive-bg-hover)}
ul.ob-list{list-style:none;padding:0}
ul.ob-list li{padding:.25rem 0;border-bottom:1px dashed var(--dsw-alias-border-l1)}
.meta{color:var(--dsw-alias-label-tertiary);font-size:calc(var(--dsh-content-font-size,16px) * 0.75)}
.ob-toc ol{list-style:none;padding-left:0}
.ob-toc .l3{padding-left:1em}
.ob-toc .l4{padding-left:2em}
.ob-toc .l5{padding-left:3em}
.ob-toc .l6{padding-left:4em}`
